export default function data() {
  return;
}

export const usersData = [
  {
    id: 0,
    name: "John Doe",
    registered: "2018/01/01",
    role: "Convidado",
    status: "Pendente",
    username: "john.doe",
  },
  {
    id: 1,
    name: "Samppa Nori",
    registered: "2018/01/01",
    role: "Membro",
    status: "Ativo",
    username: "samppa.nori",
  },
  {
    id: 2,
    name: "Estavan Lykos",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banido",
    username: "estavan.lykos",
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inativo",
    username: "chetan.mohamed",
  },
  {
    id: 4,
    name: "Derick Maximinus",
    registered: "2018/03/01",
    role: "Membro",
    status: "Pendente",
    username: "derick.maximinus",
  },
  {
    id: 5,
    name: "Friderik Dávid",
    registered: "2018/01/21",
    role: "Staff",
    status: "Ativo",
    username: "friderik.dávid",
  },
  {
    id: 6,
    name: "Yiorgos Avraamu",
    registered: "2018/01/01",
    role: "Membro",
    status: "Ativo",
    username: "yiorgos.avraamu",
  },
  {
    id: 7,
    name: "Avram Tarasios",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banido",
    username: "avram.tarasios",
  },
  {
    id: 8,
    name: "Quintin Ed",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inativo",
    username: "quintin.ed",
  },
  {
    id: 9,
    name: "Enéas Kwadwo",
    registered: "2018/03/01",
    role: "Membro",
    status: "Pendente",
    username: "enéas.kwadwo",
  },
  {
    id: 10,
    name: "Agapetus Tadeás",
    registered: "2018/01/21",
    role: "Staff",
    status: "Ativo",
    username: "Agapetus.tadeás",
  },
  {
    id: 11,
    name: "Carwyn Fachtna",
    registered: "2018/01/01",
    role: "Membro",
    status: "Ativo",
    username: "carwyn.fachtna",
  },
  {
    id: 12,
    name: "Nehemiah Tatius",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banido",
    username: "nehemiah.tatius",
  },
  {
    id: 13,
    name: "Ebbe Gemariah",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inativo",
    username: "ebbe.gemariah",
  },
  {
    id: 14,
    name: "Eustorgios Amulius",
    registered: "2018/03/01",
    role: "Membro",
    status: "Pendente",
    username: "eustorgios.amulius",
  },
  {
    id: 15,
    name: "Leopold Gáspár",
    registered: "2018/01/21",
    role: "Staff",
    status: "Ativo",
    username: "leopold.gaspár",
  },
  {
    id: 16,
    name: "Pompeius René",
    registered: "2018/01/01",
    role: "Membro",
    status: "Ativo",
    username: "pompeius.rené",
  },
  {
    id: 17,
    name: "Pacjo Jadon",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banido",
    username: "pacjo.jadon",
  },
  {
    id: 18,
    name: "Micheal Mercurius",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inativo",
    username: "micheal.mercurius",
  },
  {
    id: 19,
    name: "Ganesha Dubhghall",
    registered: "2018/03/01",
    role: "Membro",
    status: "Pendente",
    username: "ganesha.dubhghall",
  },
  {
    id: 20,
    name: "Hiroto Simun",
    registered: "2018/01/21",
    role: "Staff",
    status: "Ativo",
    username: "hiroto.simun",
  },
  {
    id: 21,
    name: "Vishnu Serghei",
    registered: "2018/01/01",
    role: "Membro",
    status: "Ativo",
    username: "vishnu.serghei",
  },
  {
    id: 22,
    name: "Zbynek Phoibos",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banido",
    username: "zbynek.phoibos",
  },
  {
    id: 23,
    name: "Aulus Agmundr",
    registered: "2018/01/01",
    role: "Membro",
    status: "Pendente",
    username: "aulus.agmundr",
  },
];

export const usersStatus = [
  {
    id: 0,
    description: "Ativo",
  },
  {
    id: 1,
    description: "Inativo",
  },
  {
    id: 2,
    description: "Pendente",
  },
  {
    id: 3,
    description: "Banido",
  },
];
